version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./application/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./application/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"
      - "5173"
    ports:
      - "5173:5173"

  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASS: 'password'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
  adminer:
    container_name: "adminer"
    init: true
    image: adminer
    ports:
      - '8888:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'mysql'
      # ADMINER_DEFAULT_DB_HOST: $DB_HOST
      # ADMINER_DEFAULT_DB: $DB_DATABASE
      # ADMINER_DEFAULT_USERNAME: $DB_USERNAME
      # ADMINER_DEFAULT_PASSWORD: $DB_PASSWORD
    networks:
      - internal
  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui

networks:
  internal:
    driver: bridge
